# Generated by Django 6.0.1 on 2026-01-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('style', models.CharField(default='2d_cute', max_length=50)),
                ('language', models.CharField(default='bn', max_length=10)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
