# Generated by Django 6.0.1 on 2026-01-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Scene order in timeline'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='data',
            field=models.JSONField(help_text='Generated scene data (background, characters, narration, duration)'),
        ),
    ]
